### ISSUE TITLE
yum-config-manager: command not found

### ISSUE THREAD

**Issue by ccaudill** [ngds/install-and-run#18]
yum install -y libxml2-2.9.0 gdal-1.9.2 gdal-python-1.9.2 gdal-devel-1.9.2 yum-utils

next error - trying to run the install command on line 8 of the instructions...

![gin-error](https://cloud.githubusercontent.com/assets/3188489/5254690/4786ad64-7970-11e4-94ba-13c974d68df1.JPG)

@FuhuXia 
@lukejbuckley

**Comment by emilianoavendano** [comment]
in order to "yum install yum-utils" work, you need the yum-utils before:

yum install yum-utils
