### ISSUE TITLE
Edits to records result in metadata being deleted in UI

### ISSUE THREAD

**Issue by ccaudill** [ngds/install-and-run#20]
Hi Christy –
I’m attaching a couple of photos of a bug in your GINStack web software.
When I went back to edit one of the entries I had previously published it wiped out most of the information in the Author, Resource Contact, etc. entries.
It’s going to be very annoying if I have to re-do the whole record each time I need to make a correction.
Thanks,
Luke

@lukejbuckley 
@FuhuXia 

After Editing
![afterediting](https://cloud.githubusercontent.com/assets/3188489/5397433/b54220dc-8117-11e4-99c0-4541cf47adfe.PNG)

Before Editing
![beforeediting](https://cloud.githubusercontent.com/assets/3188489/5397444/bdc186f8-8117-11e4-97e9-3276f93f79f5.PNG)

**Comment by ccaudill** [comment]
@lukejbuckley It looks like you just run the update script: https://github.com/ngds/install-and-run#updating-ngds
It might be worth it to wait until the GeoServer (services publication) code is finished, though!

**Comment by lukejbuckley** [comment]
I think I’ll wait. Looks like several other issues are being worked on. Thanks!

Luke Buckley | Computer Software Engineer
MBMG | Montana Tech
1300 W Park St, NRB 329 A | Butte, MT 59701

**Comment by smrazgs** [comment]
see https://github.com/ngds/ckanext-ngds/issues/635
