### ISSUE TITLE
Local host and 5432 port blocks causing harvest not to work

### ISSUE THREAD

**Issue by ccaudill** [ngds/install-and-run#25]
https://github.com/ngds/install-and-run/issues/22
See comments from me since 3/19

In both our installs as well as MTs, we had to do the following to get connections to Postgres and to harvest:
run commands:
iptables -I INPUT 1 -p tcp --dport 5432 -j ACCEPT
service iptables save
service iptables restart

Then, you have to get into the /var/lib/pgsql/9.1/data/postgresql.conf and edit those files.

Today, @FuhuXia set up servers without having to do this - why is this happening for us and not you? We'll wipe and do a fresh install with a pipe for the messages on install to go to a file for your review, just in case some error is happening on install and getting overlooked.

**Comment by ccaudill** [comment]
Our servers were wiped and re-installed today. CKAN-CKAN harvest is still NOT working.
Here's the working CSW capabilities:
http://test.geothermaldata.org/csw?request=GetCapabilities&Service=CSW&Version=2.0.2
But the error on harvest is still the same as before the reinstall:
![harvesterror](https://cloud.githubusercontent.com/assets/3188489/6854053/0705f7b8-d3ac-11e4-95a0-32c56bf0bb19.PNG)

We did this after our state firewall issues were sorted out to show you that the /var/lib/pgsql/9.1/data/postgresql.conf has port 5432 access commented out, and /var/lib/pgsql/9.1/data/pg_hba.conf does not allow traffic either. MT has the same issues with their install too. Also, my bet is we have to run the
 
iptables -I INPUT 1 -p tcp --dport 5432 -j ACCEPT
service iptables save
service iptables restart

commands too. This was a fresh install - if you want root access please let me know and I will provide through email.

**Comment by ccaudill** [comment]
ftp://AZGS:sharefiles@secureftp.azgs.az.gov/AZGS/ccaudill/postgresql.conf
ftp://AZGS:sharefiles@secureftp.azgs.az.gov/AZGS/ccaudill/pg_hba.conf
The username is: AZGS
The password is: sharefiles

**Comment by smrazgs** [comment]
can we harvest from http://uat-ngds.reisys.com/

**Comment by dan-olaru-reisys** [comment]
@ccaudill I just talked to Fuhu about this. Can we have a clean instance to that @FuhuXia  can install the rpm by himself and try to debug (also #22 )

final.geothermaldata.org should work (clean instance of centos 6.6)

**Comment by smrazgs** [comment]
Sorry, clean instance to what?  I'm not sure what you need.

**Comment by dan-olaru-reisys** [comment]
@smrazgs  virtual server instance with minimal centos 6.6 installed on it. @ccaudill

**Comment by smrazgs** [comment]
clean server up and running,

**Comment by ccaudill** [comment]
Fuhu has tested and harvest is working to and from. Just asked AL (Denise Hills) to dump and reinstall her GINstack to ensure we can harvest from that. It's close!

**Comment by smrazgs** [comment]
AL harvest worked, this is resolved, close (if there's some other detail, make new issue)
